spring:
  profiles:
    include: jwt, oauth2, aws

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@jingyulog.hoauz.mongodb.net/?retryWrites=true&w=majority&appName=jingyulog
      database: jingyulog
      auto-index-creation: true

  redis:
    host: localhost
    port: 6379
