name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'zulu'

    - name: Create .env file from secrets
      run: |
        echo "${{ secrets.BACK_APPLICATION }}" > backend/.env

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x backend/gradlew

    - name: Build with Gradle
      working-directory: backend
      run: ./gradlew build -x test

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${EC2_KEY}" > ec2_key.pem
        chmod 400 ec2_key.pem
        scp -i ec2_key.pem backend/build/libs/your-app.jar ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/your-app.jar
        ssh -i ec2_key.pem ${EC2_USER}@${EC2_HOST} "sudo systemctl restart your-app-service"
